# Generated by Django 2.0.2 on 2019-04-09 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('device_serial', models.CharField(max_length=255)),
                ('occupation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vb_meter', models.CharField(max_length=255)),
                ('va_meter', models.CharField(max_length=255)),
                ('vin_house', models.CharField(max_length=255)),
                ('cb_meter', models.CharField(max_length=255)),
                ('ca_meter', models.CharField(max_length=255)),
                ('cin_house', models.CharField(max_length=255)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('location', models.CharField(default='Kampala', max_length=255)),
                ('energy', models.CharField(max_length=255)),
                ('client', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='meter_data.Client')),
            ],
        ),
    ]
