# Generated by Django 2.0.2 on 2019-04-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_serial', models.CharField(max_length=255)),
                ('vb_meter', models.CharField(max_length=255)),
                ('va_meter', models.CharField(max_length=255)),
                ('vin_house', models.CharField(max_length=255)),
                ('cb_meter', models.CharField(max_length=255)),
                ('ca_meter', models.CharField(max_length=255)),
                ('cin_house', models.CharField(max_length=255)),
                ('energy', models.CharField(max_length=255)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
            ],
        ),
    ]
