# Generated by Django 2.0.2 on 2019-04-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter_data', '0002_auto_20190428_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='latitude',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='data',
            name='longitude',
            field=models.CharField(max_length=255),
        ),
    ]
