# Generated by Django 2.0.2 on 2019-04-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter_data', '0002_data_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='location',
            field=models.CharField(default='Kampala', max_length=255),
        ),
    ]
